---
title: "Dimensionality Reduction - IP"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(FactoMineR)
library(tidyverse)
library(factoextra)
```

```{r}
# Load data
sales = read.csv('Supermarket_Dataset_1_Sales_Data.csv')
head(sales)
```
The Tax and gross.income columns have the same values

```{r}
# Confirm the above claim
all(sales$Tax == sales$gross.income)
```

```{r}
# Removing the income column
sales <- sales[-c(14)]
```


```{r}
str(sales)
```
```{r}
head(sales)
```

```{r}
summary(sales[, -c(1,9)])
```

```{r}
# Reordering columns
sales <- sales[, c(2,3,4,5,11,6,7,8,12,13)]
row.names(sales) <- sales$Invoice.ID

# Perform PCA on qualitative variables
pca <- prcomp(sales[, c(6:10)], scale = TRUE)
```

```{r}
summary(pca)
```
PC1 explains 58.7% of the variance in the data

```{r}
# Visualize variances of each principal component
fviz_eig(pca)
```

The first principal component explains over 58.7% variation in the dataset. 
```{r}
fviz_pca_var(pca,
             col.var ="contrib", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```
```{r}
# Perform factor analysis
famd <- FAMD(sales.new,ncp = 7, graph = F)
```

```{r}
# eigen values for each dimension
get_eigenvalue(famd)
```

```{r}
fviz_eig(famd)
```
```{r}
# Plotting the variables
fviz_famd_var(famd, repel = TRUE) 

# Contribution to the First Dimension
fviz_contrib(famd, "var", axes = 1)

# Contribution to the Second Dimension
fviz_contrib(famd, "var", axes = 2)
```
**Observations**
1. Tax, cogs and Total contributes most to the First Dimension
2. Gender, Product line, Payment and Branch contribute most to the Second Dimension